<?php

use Illuminate\Database\Seeder;

class BasicDataTypesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('data_types')->delete();
        
        \DB::table('data_types')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'users',
                'slug' => 'users',
                'display_name_singular' => 'User',
                'display_name_plural' => 'Users',
                'icon' => 'voyager-person',
                'model_name' => 'TCG\\Voyager\\Models\\User',
                'policy_name' => 'TCG\\Voyager\\Policies\\UserPolicy',
                'controller' => 'TCG\\Voyager\\Http\\Controllers\\VoyagerUserController',
                'description' => '',
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => NULL,
                'created_at' => '2019-07-24 21:47:40',
                'updated_at' => '2019-07-24 21:47:40',
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'menus',
                'slug' => 'menus',
                'display_name_singular' => 'Menu',
                'display_name_plural' => 'Menus',
                'icon' => 'voyager-list',
                'model_name' => 'TCG\\Voyager\\Models\\Menu',
                'policy_name' => NULL,
                'controller' => '',
                'description' => '',
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => NULL,
                'created_at' => '2019-07-24 21:47:40',
                'updated_at' => '2019-07-24 21:47:40',
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'roles',
                'slug' => 'roles',
                'display_name_singular' => 'Role',
                'display_name_plural' => 'Roles',
                'icon' => 'voyager-lock',
                'model_name' => 'TCG\\Voyager\\Models\\Role',
                'policy_name' => NULL,
                'controller' => '',
                'description' => '',
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => NULL,
                'created_at' => '2019-07-24 21:47:40',
                'updated_at' => '2019-07-24 21:47:40',
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'category',
                'slug' => 'category',
                'display_name_singular' => 'Category',
                'display_name_plural' => 'Categories',
                'icon' => 'voyager-categories',
                'model_name' => 'App\\Models\\Category',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 1,
                'details' => '{"order_column":null,"order_display_column":"name","order_direction":"desc","default_search_key":"name","scope":null}',
                'created_at' => '2019-07-24 22:03:09',
                'updated_at' => '2019-07-25 15:25:16',
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'product',
                'slug' => 'product',
                'display_name_singular' => 'Product',
                'display_name_plural' => 'Products',
                'icon' => 'voyager-backpack',
                'model_name' => 'App\\Models\\Product',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 1,
                'details' => '{"order_column":null,"order_display_column":"name","order_direction":"desc","default_search_key":"name","scope":null}',
                'created_at' => '2019-07-24 22:21:02',
                'updated_at' => '2019-07-24 22:37:20',
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'discount',
                'slug' => 'discount',
                'display_name_singular' => 'Discount',
                'display_name_plural' => 'Discounts',
                'icon' => 'voyager-tag',
                'model_name' => 'App\\Models\\Discount',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 1,
                'details' => '{"order_column":null,"order_display_column":"name","order_direction":"desc","default_search_key":"name","scope":null}',
                'created_at' => '2019-07-24 22:42:46',
                'updated_at' => '2019-07-25 01:46:25',
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'insurance_company',
                'slug' => 'insurance-company',
                'display_name_singular' => 'Insurance Company',
                'display_name_plural' => 'Insurance Companies',
                'icon' => 'voyager-heart',
                'model_name' => 'App\\Models\\Insurance_company',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 1,
                'details' => '{"order_column":null,"order_display_column":"name","order_direction":"desc","default_search_key":"name"}',
                'created_at' => '2019-07-25 13:50:04',
                'updated_at' => '2019-07-25 13:50:04',
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'refund',
                'slug' => 'refund',
                'display_name_singular' => 'Refund',
                'display_name_plural' => 'Refunds',
                'icon' => 'voyager-refresh',
                'model_name' => 'App\\Models\\Refund',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 1,
                'details' => '{"order_column":null,"order_display_column":"id","order_direction":"desc","default_search_key":"reason","scope":null}',
                'created_at' => '2019-07-25 14:25:04',
                'updated_at' => '2019-07-25 14:31:21',
            ),
            8 => 
            array (
                'id' => 9,
                'name' => 'payment_method',
                'slug' => 'payment-method',
                'display_name_singular' => 'Payment Method',
                'display_name_plural' => 'Payment Methods',
                'icon' => 'voyager-credit-cards',
                'model_name' => 'App\\Models\\Payment_method',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 1,
                'details' => '{"order_column":null,"order_display_column":"name","order_direction":"desc","default_search_key":"name"}',
                'created_at' => '2019-07-25 14:33:03',
                'updated_at' => '2019-07-25 14:33:03',
            ),
            9 => 
            array (
                'id' => 10,
                'name' => 'person',
                'slug' => 'client',
                'display_name_singular' => 'Client',
                'display_name_plural' => 'Clients',
                'icon' => 'voyager-person',
                'model_name' => 'App\\Models\\Person',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 1,
                'details' => '{"order_column":null,"order_display_column":"identification","order_direction":"desc","default_search_key":"identification","scope":null}',
                'created_at' => '2019-07-25 14:38:25',
                'updated_at' => '2019-07-25 15:37:32',
            ),
            10 => 
            array (
                'id' => 12,
                'name' => 'state',
                'slug' => 'state',
                'display_name_singular' => 'State',
                'display_name_plural' => 'States',
                'icon' => 'f5a0',
                'model_name' => 'App\\Models\\State',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 1,
                'details' => '{"order_column":null,"order_display_column":"name","order_direction":"desc","default_search_key":"name","scope":null}',
                'created_at' => '2019-07-25 15:09:17',
                'updated_at' => '2019-07-25 15:12:08',
            ),
            11 => 
            array (
                'id' => 13,
                'name' => 'city',
                'slug' => 'city',
                'display_name_singular' => 'City',
                'display_name_plural' => 'Cities',
                'icon' => 'voyager-location',
                'model_name' => 'App\\Models\\City',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 1,
                'details' => '{"order_column":null,"order_display_column":"name","order_direction":"desc","default_search_key":"name","scope":null}',
                'created_at' => '2019-07-25 15:14:52',
                'updated_at' => '2019-07-25 15:16:08',
            ),
            12 => 
            array (
                'id' => 14,
                'name' => 'invoice',
                'slug' => 'invoice',
                'display_name_singular' => 'Invoice',
                'display_name_plural' => 'Invoices',
                'icon' => 'voyager-buy',
                'model_name' => 'App\\Models\\Invoice',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 1,
                'details' => '{"order_column":null,"order_display_column":"id","order_direction":"desc","default_search_key":"id","scope":null}',
                'created_at' => '2019-07-25 15:18:19',
                'updated_at' => '2019-07-25 15:20:54',
            ),
        ));
        
        
    }
}