<?php

use Illuminate\Database\Seeder;

class DataRowsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('data_rows')->delete();
        
        \DB::table('data_rows')->insert(array (
            0 => 
            array (
                'id' => 1,
                'data_type_id' => 1,
                'field' => 'id',
                'type' => 'number',
                'display_name' => 'ID',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            1 => 
            array (
                'id' => 2,
                'data_type_id' => 1,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Name',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 2,
            ),
            2 => 
            array (
                'id' => 3,
                'data_type_id' => 1,
                'field' => 'email',
                'type' => 'text',
                'display_name' => 'Email',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 4,
            ),
            3 => 
            array (
                'id' => 4,
                'data_type_id' => 1,
                'field' => 'password',
                'type' => 'password',
                'display_name' => 'Password',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{}',
                'order' => 5,
            ),
            4 => 
            array (
                'id' => 5,
                'data_type_id' => 1,
                'field' => 'remember_token',
                'type' => 'text',
                'display_name' => 'Remember Token',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 6,
            ),
            5 => 
            array (
                'id' => 6,
                'data_type_id' => 1,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 7,
            ),
            6 => 
            array (
                'id' => 7,
                'data_type_id' => 1,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 9,
            ),
            7 => 
            array (
                'id' => 8,
                'data_type_id' => 1,
                'field' => 'avatar',
                'type' => 'image',
                'display_name' => 'Avatar',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 10,
            ),
            8 => 
            array (
                'id' => 9,
                'data_type_id' => 1,
                'field' => 'user_belongsto_role_relationship',
                'type' => 'relationship',
                'display_name' => 'Role',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"model":"TCG\\\\Voyager\\\\Models\\\\Role","table":"roles","type":"belongsTo","column":"role_id","key":"id","label":"display_name","pivot_table":"roles","pivot":"0","taggable":"0"}',
                'order' => 13,
            ),
            9 => 
            array (
                'id' => 10,
                'data_type_id' => 1,
                'field' => 'user_belongstomany_role_relationship',
                'type' => 'relationship',
                'display_name' => 'Roles',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"model":"TCG\\\\Voyager\\\\Models\\\\Role","table":"roles","type":"belongsToMany","column":"id","key":"id","label":"display_name","pivot_table":"user_roles","pivot":"1","taggable":"0"}',
                'order' => 15,
            ),
            10 => 
            array (
                'id' => 11,
                'data_type_id' => 1,
                'field' => 'settings',
                'type' => 'hidden',
                'display_name' => 'Settings',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 16,
            ),
            11 => 
            array (
                'id' => 12,
                'data_type_id' => 2,
                'field' => 'id',
                'type' => 'number',
                'display_name' => 'ID',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 1,
            ),
            12 => 
            array (
                'id' => 13,
                'data_type_id' => 2,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Name',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 2,
            ),
            13 => 
            array (
                'id' => 14,
                'data_type_id' => 2,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 3,
            ),
            14 => 
            array (
                'id' => 15,
                'data_type_id' => 2,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 4,
            ),
            15 => 
            array (
                'id' => 16,
                'data_type_id' => 3,
                'field' => 'id',
                'type' => 'number',
                'display_name' => 'ID',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 1,
            ),
            16 => 
            array (
                'id' => 17,
                'data_type_id' => 3,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Name',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 2,
            ),
            17 => 
            array (
                'id' => 18,
                'data_type_id' => 3,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 3,
            ),
            18 => 
            array (
                'id' => 19,
                'data_type_id' => 3,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => NULL,
                'order' => 4,
            ),
            19 => 
            array (
                'id' => 20,
                'data_type_id' => 3,
                'field' => 'display_name',
                'type' => 'text',
                'display_name' => 'Display Name',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => NULL,
                'order' => 5,
            ),
            20 => 
            array (
                'id' => 21,
                'data_type_id' => 1,
                'field' => 'role_id',
                'type' => 'text',
                'display_name' => 'Role',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 12,
            ),
            21 => 
            array (
                'id' => 22,
                'data_type_id' => 4,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            22 => 
            array (
                'id' => 23,
                'data_type_id' => 4,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Name',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"validation":{"rule":"required|min:2|max:250"}}',
                'order' => 4,
            ),
            23 => 
            array (
                'id' => 24,
                'data_type_id' => 4,
                'field' => 'description',
                'type' => 'rich_text_box',
                'display_name' => 'Description',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":"max:1000"}}',
                'order' => 5,
            ),
            24 => 
            array (
                'id' => 25,
                'data_type_id' => 4,
                'field' => 'parent_category_id',
                'type' => 'text',
                'display_name' => 'Parent Category Id',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 2,
            ),
            25 => 
            array (
                'id' => 26,
                'data_type_id' => 4,
                'field' => 'deleted_at',
                'type' => 'timestamp',
                'display_name' => 'Deleted At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 6,
            ),
            26 => 
            array (
                'id' => 27,
                'data_type_id' => 4,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 7,
            ),
            27 => 
            array (
                'id' => 28,
                'data_type_id' => 4,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 8,
            ),
            28 => 
            array (
                'id' => 29,
                'data_type_id' => 4,
                'field' => 'category_hasmany_category_relationship',
                'type' => 'relationship',
                'display_name' => 'Parent Categories',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\Models\\\\Category","table":"category","type":"belongsTo","column":"parent_category_id","key":"id","label":"name","pivot_table":"category","pivot":"0","taggable":"on"}',
                'order' => 3,
            ),
            29 => 
            array (
                'id' => 30,
                'data_type_id' => 5,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            30 => 
            array (
                'id' => 31,
                'data_type_id' => 5,
                'field' => 'purchase_price',
                'type' => 'number',
                'display_name' => 'Purchase Price',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":"numeric|min:0|max:999.999.999,999"},"default":"0"}',
                'order' => 3,
            ),
            31 => 
            array (
                'id' => 32,
                'data_type_id' => 5,
                'field' => 'sale_price',
                'type' => 'number',
                'display_name' => 'Sale Price',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":"numeric|min:0|max:999.999.999,999"},"default":"0"}',
                'order' => 4,
            ),
            32 => 
            array (
                'id' => 33,
                'data_type_id' => 5,
                'field' => 'amount',
                'type' => 'number',
                'display_name' => 'Amount',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":"integer|min:0|max:999.999.999"},"default":"0"}',
                'order' => 5,
            ),
            33 => 
            array (
                'id' => 35,
                'data_type_id' => 5,
                'field' => 'deleted_at',
                'type' => 'timestamp',
                'display_name' => 'Deleted At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 8,
            ),
            34 => 
            array (
                'id' => 36,
                'data_type_id' => 5,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 9,
            ),
            35 => 
            array (
                'id' => 37,
                'data_type_id' => 5,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 10,
            ),
            36 => 
            array (
                'id' => 38,
                'data_type_id' => 4,
                'field' => 'category_belongstomany_product_relationship',
                'type' => 'relationship',
                'display_name' => 'Products',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\Models\\\\Product","table":"product","type":"belongsToMany","column":"id","key":"id","label":"name","pivot_table":"product_category","pivot":"1","taggable":"0"}',
                'order' => 9,
            ),
            37 => 
            array (
                'id' => 39,
                'data_type_id' => 5,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Name',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"validation":{"rule":"required|min:2|max:250"}}',
                'order' => 2,
            ),
            38 => 
            array (
                'id' => 40,
                'data_type_id' => 5,
                'field' => 'description',
                'type' => 'rich_text_box',
                'display_name' => 'Description',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"validation":{"rule":"max:1000"}}',
                'order' => 7,
            ),
            39 => 
            array (
                'id' => 41,
                'data_type_id' => 5,
                'field' => 'product_belongstomany_category_relationship',
                'type' => 'relationship',
                'display_name' => 'category',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\Models\\\\Category","table":"category","type":"belongsToMany","column":"id","key":"id","label":"name","pivot_table":"product_category","pivot":"1","taggable":"on"}',
                'order' => 6,
            ),
            40 => 
            array (
                'id' => 42,
                'data_type_id' => 6,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            41 => 
            array (
                'id' => 43,
                'data_type_id' => 6,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Name',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"validation":{"rule":"required|min:2|max:250"}}',
                'order' => 2,
            ),
            42 => 
            array (
                'id' => 44,
                'data_type_id' => 6,
                'field' => 'description',
                'type' => 'text_area',
                'display_name' => 'Description',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":"max:1000"}}',
                'order' => 3,
            ),
            43 => 
            array (
                'id' => 45,
                'data_type_id' => 6,
                'field' => 'percentage',
                'type' => 'number',
                'display_name' => 'Percentage',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":"required|numeric|min:0|max:100"}}',
                'order' => 4,
            ),
            44 => 
            array (
                'id' => 46,
                'data_type_id' => 6,
                'field' => 'deleted_at',
                'type' => 'timestamp',
                'display_name' => 'Deleted At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 5,
            ),
            45 => 
            array (
                'id' => 47,
                'data_type_id' => 6,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 6,
            ),
            46 => 
            array (
                'id' => 48,
                'data_type_id' => 6,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 7,
            ),
            47 => 
            array (
                'id' => 49,
                'data_type_id' => 7,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            48 => 
            array (
                'id' => 50,
                'data_type_id' => 7,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Name',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"validation":{"rule":"required|min:2|max:250"}}',
                'order' => 2,
            ),
            49 => 
            array (
                'id' => 51,
                'data_type_id' => 7,
                'field' => 'identification',
                'type' => 'text',
                'display_name' => 'Identification',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":"max:250"}}',
                'order' => 3,
            ),
            50 => 
            array (
                'id' => 52,
                'data_type_id' => 7,
                'field' => 'type',
                'type' => 'select_dropdown',
                'display_name' => 'Type',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"default":"unknown","options":{"unknown":"unknown","bhc":"Basic healt care","ehc":"Emergency health care"},"validation":{"rule":"max:50"}}',
                'order' => 4,
            ),
            51 => 
            array (
                'id' => 53,
                'data_type_id' => 7,
                'field' => 'deleted_at',
                'type' => 'timestamp',
                'display_name' => 'Deleted At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 5,
            ),
            52 => 
            array (
                'id' => 54,
                'data_type_id' => 7,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 6,
            ),
            53 => 
            array (
                'id' => 55,
                'data_type_id' => 7,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 7,
            ),
            54 => 
            array (
                'id' => 56,
                'data_type_id' => 8,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Refund number',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            55 => 
            array (
                'id' => 57,
                'data_type_id' => 8,
                'field' => 'reason',
                'type' => 'text',
                'display_name' => 'Reason',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"validation":{"rule":"required|min:5|max:250"}}',
                'order' => 3,
            ),
            56 => 
            array (
                'id' => 58,
                'data_type_id' => 8,
                'field' => 'description',
                'type' => 'rich_text_box',
                'display_name' => 'Description',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":"max:1000"}}',
                'order' => 4,
            ),
            57 => 
            array (
                'id' => 59,
                'data_type_id' => 8,
                'field' => 'amount',
                'type' => 'text',
                'display_name' => 'Amount',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"validation":{"rule":"required|min:1|max:9999"}}',
                'order' => 5,
            ),
            58 => 
            array (
                'id' => 60,
                'data_type_id' => 8,
                'field' => 'date',
                'type' => 'text',
                'display_name' => 'Date',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"validation":{"rule":"before_or_equal:2019-01-01"}}',
                'order' => 6,
            ),
            59 => 
            array (
                'id' => 61,
                'data_type_id' => 8,
                'field' => 'detail_id',
                'type' => 'text',
                'display_name' => 'Detail Id',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 2,
            ),
            60 => 
            array (
                'id' => 62,
                'data_type_id' => 8,
                'field' => 'deleted_at',
                'type' => 'timestamp',
                'display_name' => 'Deleted At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 7,
            ),
            61 => 
            array (
                'id' => 63,
                'data_type_id' => 8,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 8,
            ),
            62 => 
            array (
                'id' => 64,
                'data_type_id' => 8,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 9,
            ),
            63 => 
            array (
                'id' => 65,
                'data_type_id' => 8,
                'field' => 'refund_belongsto_detail_relationship',
                'type' => 'relationship',
                'display_name' => 'Detail',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\Models\\\\Detail","table":"detail","type":"belongsTo","column":"detail_id","key":"id","label":"product_id","pivot_table":"category","pivot":"0","taggable":"0"}',
                'order' => 10,
            ),
            64 => 
            array (
                'id' => 66,
                'data_type_id' => 9,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            65 => 
            array (
                'id' => 67,
                'data_type_id' => 9,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Name',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"validation":{"rule":"required|min:2|max:250"}}',
                'order' => 2,
            ),
            66 => 
            array (
                'id' => 68,
                'data_type_id' => 9,
                'field' => 'description',
                'type' => 'text',
                'display_name' => 'Description',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":"max:1000"}}',
                'order' => 3,
            ),
            67 => 
            array (
                'id' => 69,
                'data_type_id' => 9,
                'field' => 'deleted_at',
                'type' => 'timestamp',
                'display_name' => 'Deleted At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 4,
            ),
            68 => 
            array (
                'id' => 70,
                'data_type_id' => 9,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 5,
            ),
            69 => 
            array (
                'id' => 71,
                'data_type_id' => 9,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 6,
            ),
            70 => 
            array (
                'id' => 72,
                'data_type_id' => 10,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            71 => 
            array (
                'id' => 73,
                'data_type_id' => 10,
                'field' => 'identification',
                'type' => 'text',
                'display_name' => 'Identification',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":"max:50"}}',
                'order' => 4,
            ),
            72 => 
            array (
                'id' => 74,
                'data_type_id' => 10,
                'field' => 'identification_type',
                'type' => 'select_dropdown',
                'display_name' => 'Identification Type',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"default":"unknown","options":{"unknown":"unknown","passport":"passport","officialidentification":"official identification","other":"other"},"validation":{"rule":"max:50"}}',
                'order' => 5,
            ),
            73 => 
            array (
                'id' => 75,
                'data_type_id' => 10,
                'field' => 'photo',
                'type' => 'image',
                'display_name' => 'Photo',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"quality":"70%"}',
                'order' => 6,
            ),
            74 => 
            array (
                'id' => 76,
                'data_type_id' => 10,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'First Name',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":"required|min:2|max:250"}}',
                'order' => 7,
            ),
            75 => 
            array (
                'id' => 77,
                'data_type_id' => 10,
                'field' => 'middle_name',
                'type' => 'text',
                'display_name' => 'Middle Name',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":"required|min:2|max:250"}}',
                'order' => 8,
            ),
            76 => 
            array (
                'id' => 78,
                'data_type_id' => 10,
                'field' => 'first_surname',
                'type' => 'text',
                'display_name' => 'First Surname',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":"required|min:2|max:250"}}',
                'order' => 9,
            ),
            77 => 
            array (
                'id' => 79,
                'data_type_id' => 10,
                'field' => 'second_surname',
                'type' => 'text',
                'display_name' => 'Second Surname',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":"max:250"}}',
                'order' => 10,
            ),
            78 => 
            array (
                'id' => 80,
                'data_type_id' => 10,
                'field' => 'blood_group_rh',
                'type' => 'select_dropdown',
                'display_name' => 'Blood Group and Rh',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"default":"unknown","options":{"unknown":"unknown","A+":"A+","A-":"A-","B+":"B+","B-":"B-","AB+":"AB+","AB-":"AB-","O+":"O+","O-":"O-"},"validation":{"rule":"max:3"}}',
                'order' => 11,
            ),
            79 => 
            array (
                'id' => 81,
                'data_type_id' => 10,
                'field' => 'insurance_company_id',
                'type' => 'text',
                'display_name' => 'Insurance Company Id',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 2,
            ),
            80 => 
            array (
                'id' => 82,
                'data_type_id' => 10,
                'field' => 'city_birth_id',
                'type' => 'text',
                'display_name' => 'City Birth Id',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 3,
            ),
            81 => 
            array (
                'id' => 83,
                'data_type_id' => 10,
                'field' => 'birthdate',
                'type' => 'date',
                'display_name' => 'Birthdate',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":"after_or_equal:01-01-1900"}}',
                'order' => 12,
            ),
            82 => 
            array (
                'id' => 84,
                'data_type_id' => 10,
                'field' => 'address',
                'type' => 'text',
                'display_name' => 'Address',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":"max:250"}}',
                'order' => 14,
            ),
            83 => 
            array (
                'id' => 85,
                'data_type_id' => 10,
                'field' => 'email',
                'type' => 'text',
                'display_name' => 'Contact Email',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":"email|max:250"}}',
                'order' => 15,
            ),
            84 => 
            array (
                'id' => 86,
                'data_type_id' => 10,
                'field' => 'phone',
                'type' => 'text',
                'display_name' => 'Phone',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":"max:250"}}',
                'order' => 16,
            ),
            85 => 
            array (
                'id' => 87,
                'data_type_id' => 10,
                'field' => 'gender',
                'type' => 'select_dropdown',
                'display_name' => 'Gender',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"default":"unknown","options":{"unknown":"unknown","Female":"Female","Male":"Male"},"description":"We require this field because one of the many ways we use this information is in communicationg with the client insurance company. Please make sure you provide here is the same as what you insurance provider has on file."}',
                'order' => 17,
            ),
            86 => 
            array (
                'id' => 88,
                'data_type_id' => 10,
                'field' => 'deleted_at',
                'type' => 'timestamp',
                'display_name' => 'Deleted At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 18,
            ),
            87 => 
            array (
                'id' => 89,
                'data_type_id' => 10,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 19,
            ),
            88 => 
            array (
                'id' => 90,
                'data_type_id' => 10,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 20,
            ),
            89 => 
            array (
                'id' => 91,
                'data_type_id' => 10,
                'field' => 'person_hasone_user_relationship',
                'type' => 'relationship',
                'display_name' => 'Account Email',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{"model":"App\\\\User","table":"users","type":"hasOne","column":"person_id","key":"id","label":"email","pivot_table":"category","pivot":"0","taggable":"0"}',
                'order' => 21,
            ),
            90 => 
            array (
                'id' => 92,
                'data_type_id' => 10,
                'field' => 'person_hasone_invoice_relationship',
                'type' => 'relationship',
                'display_name' => 'Invoice numbers',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\Models\\\\Invoice","table":"invoice","type":"hasOne","column":"client_person_id","key":"id","label":"id","pivot_table":"category","pivot":"0","taggable":"0"}',
                'order' => 22,
            ),
            91 => 
            array (
                'id' => 93,
                'data_type_id' => 10,
                'field' => 'person_belongsto_insurance_company_relationship',
                'type' => 'relationship',
                'display_name' => 'Insurance company',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\Models\\\\Insurance_company","table":"insurance_company","type":"belongsTo","column":"insurance_company_id","key":"id","label":"name","pivot_table":"category","pivot":"0","taggable":"0"}',
                'order' => 23,
            ),
            92 => 
            array (
                'id' => 94,
                'data_type_id' => 10,
                'field' => 'person_belongsto_city_relationship',
                'type' => 'relationship',
                'display_name' => 'City of birth',
                'required' => 0,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\Models\\\\City","table":"city","type":"belongsTo","column":"city_birth_id","key":"id","label":"name","pivot_table":"category","pivot":"0","taggable":"0"}',
                'order' => 13,
            ),
            93 => 
            array (
                'id' => 95,
                'data_type_id' => 12,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            94 => 
            array (
                'id' => 96,
                'data_type_id' => 12,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Name',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"validation":{"rule":"required|min:2|max:250"}}',
                'order' => 2,
            ),
            95 => 
            array (
                'id' => 97,
                'data_type_id' => 12,
                'field' => 'deleted_at',
                'type' => 'timestamp',
                'display_name' => 'Deleted At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 3,
            ),
            96 => 
            array (
                'id' => 98,
                'data_type_id' => 12,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 4,
            ),
            97 => 
            array (
                'id' => 99,
                'data_type_id' => 12,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 5,
            ),
            98 => 
            array (
                'id' => 100,
                'data_type_id' => 12,
                'field' => 'state_hasone_city_relationship',
                'type' => 'relationship',
                'display_name' => 'city',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\Models\\\\City","table":"city","type":"hasOne","column":"state_id","key":"id","label":"name","pivot_table":"category","pivot":"0","taggable":"0"}',
                'order' => 6,
            ),
            99 => 
            array (
                'id' => 101,
                'data_type_id' => 13,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            100 => 
            array (
                'id' => 102,
                'data_type_id' => 13,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Name',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"validation":{"rule":"required|min:2|max:250"}}',
                'order' => 3,
            ),
            101 => 
            array (
                'id' => 103,
                'data_type_id' => 13,
                'field' => 'state_id',
                'type' => 'text',
                'display_name' => 'State Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 2,
            ),
            102 => 
            array (
                'id' => 104,
                'data_type_id' => 13,
                'field' => 'deleted_at',
                'type' => 'timestamp',
                'display_name' => 'Deleted At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 4,
            ),
            103 => 
            array (
                'id' => 105,
                'data_type_id' => 13,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 5,
            ),
            104 => 
            array (
                'id' => 106,
                'data_type_id' => 13,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 6,
            ),
            105 => 
            array (
                'id' => 107,
                'data_type_id' => 13,
                'field' => 'city_belongsto_state_relationship',
                'type' => 'relationship',
                'display_name' => 'state',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\Models\\\\State","table":"state","type":"belongsTo","column":"state_id","key":"id","label":"name","pivot_table":"category","pivot":"0","taggable":"0"}',
                'order' => 7,
            ),
            106 => 
            array (
                'id' => 108,
                'data_type_id' => 14,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Invoice number',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            107 => 
            array (
                'id' => 109,
                'data_type_id' => 14,
                'field' => 'client_person_id',
                'type' => 'text',
                'display_name' => 'Client Person Id',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 1,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 2,
            ),
            108 => 
            array (
                'id' => 110,
                'data_type_id' => 14,
                'field' => 'seller_user_id',
                'type' => 'text',
                'display_name' => 'Seller User Id',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 1,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 3,
            ),
            109 => 
            array (
                'id' => 111,
                'data_type_id' => 14,
                'field' => 'payment_method_id',
                'type' => 'text',
                'display_name' => 'Payment Method Id',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 1,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 4,
            ),
            110 => 
            array (
                'id' => 112,
                'data_type_id' => 14,
                'field' => 'status',
                'type' => 'checkbox',
                'display_name' => 'Status',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"on":"Paid","off":"Not paid","checked":true,"validation":{"rule":"max:50"}}',
                'order' => 5,
            ),
            111 => 
            array (
                'id' => 113,
                'data_type_id' => 14,
                'field' => 'total',
                'type' => 'text',
                'display_name' => 'Total',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{"disable":"disable"}',
                'order' => 6,
            ),
            112 => 
            array (
                'id' => 114,
                'data_type_id' => 14,
                'field' => 'deleted_at',
                'type' => 'timestamp',
                'display_name' => 'Deleted At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 7,
            ),
            113 => 
            array (
                'id' => 115,
                'data_type_id' => 14,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 8,
            ),
            114 => 
            array (
                'id' => 116,
                'data_type_id' => 14,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 9,
            ),
            115 => 
            array (
                'id' => 117,
                'data_type_id' => 14,
                'field' => 'invoice_belongsto_person_relationship',
                'type' => 'relationship',
                'display_name' => 'Client ID',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\Models\\\\Person","table":"person","type":"belongsTo","column":"client_person_id","key":"id","label":"identification","pivot_table":"category","pivot":"0","taggable":"0"}',
                'order' => 12,
            ),
            116 => 
            array (
                'id' => 118,
                'data_type_id' => 14,
                'field' => 'invoice_belongsto_user_relationship',
                'type' => 'relationship',
                'display_name' => 'Seller',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"model":"App\\\\User","table":"users","type":"belongsTo","column":"seller_user_id","key":"id","label":"name","pivot_table":"category","pivot":"0","taggable":"0"}',
                'order' => 13,
            ),
            117 => 
            array (
                'id' => 119,
                'data_type_id' => 14,
                'field' => 'invoice_hasmany_detail_relationship',
                'type' => 'relationship',
                'display_name' => 'Products',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{"model":"App\\\\Models\\\\Product","table":"product","type":"belongsToMany","column":"id","key":"id","label":"name","pivot_table":"detail","pivot":"1","taggable":"on"}',
                'order' => 11,
            ),
            118 => 
            array (
                'id' => 120,
                'data_type_id' => 17,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            119 => 
            array (
                'id' => 121,
                'data_type_id' => 17,
                'field' => 'name',
                'type' => 'text',
                'display_name' => 'Name',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"validation":{"rule":"required|min:2|max:250"}}',
                'order' => 2,
            ),
            120 => 
            array (
                'id' => 122,
                'data_type_id' => 17,
                'field' => 'photo',
                'type' => 'image',
                'display_name' => 'Photo',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"quality":"50%","max":"5000","validation":{"rule":"max:5000"}}',
                'order' => 3,
            ),
            121 => 
            array (
                'id' => 123,
                'data_type_id' => 17,
                'field' => 'description',
                'type' => 'rich_text_box',
                'display_name' => 'Description',
                'required' => 1,
                'browse' => 0,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":"max:1000"}}',
                'order' => 4,
            ),
            122 => 
            array (
                'id' => 125,
                'data_type_id' => 17,
                'field' => 'deleted_at',
                'type' => 'timestamp',
                'display_name' => 'Deleted At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 6,
            ),
            123 => 
            array (
                'id' => 126,
                'data_type_id' => 17,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 7,
            ),
            124 => 
            array (
                'id' => 127,
                'data_type_id' => 17,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 8,
            ),
            125 => 
            array (
                'id' => 128,
                'data_type_id' => 1,
                'field' => 'user_belongsto_person_relationship',
                'type' => 'relationship',
                'display_name' => 'Identification',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\Models\\\\Person","table":"person","type":"belongsTo","column":"person_id","key":"id","label":"identification","pivot_table":"category","pivot":"0","taggable":"0"}',
                'order' => 11,
            ),
            126 => 
            array (
                'id' => 129,
                'data_type_id' => 1,
                'field' => 'email_verified_at',
                'type' => 'timestamp',
                'display_name' => 'Email Verified At',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 8,
            ),
            127 => 
            array (
                'id' => 130,
                'data_type_id' => 1,
                'field' => 'deleted_at',
                'type' => 'timestamp',
                'display_name' => 'Deleted At',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 14,
            ),
            128 => 
            array (
                'id' => 131,
                'data_type_id' => 1,
                'field' => 'person_id',
                'type' => 'text',
                'display_name' => 'Person Id',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 3,
            ),
            129 => 
            array (
                'id' => 132,
                'data_type_id' => 18,
                'field' => 'id',
                'type' => 'number',
                'display_name' => 'Detail number',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 5,
            ),
            130 => 
            array (
                'id' => 133,
                'data_type_id' => 18,
                'field' => 'extra_id',
                'type' => 'number',
                'display_name' => 'Extra Id',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            131 => 
            array (
                'id' => 134,
                'data_type_id' => 18,
                'field' => 'product_id',
                'type' => 'text',
                'display_name' => 'Product Id',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{}',
                'order' => 2,
            ),
            132 => 
            array (
                'id' => 135,
                'data_type_id' => 18,
                'field' => 'invoice_id',
                'type' => 'text',
                'display_name' => 'Invoice Id',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{}',
                'order' => 3,
            ),
            133 => 
            array (
                'id' => 136,
                'data_type_id' => 18,
                'field' => 'amount',
                'type' => 'number',
                'display_name' => 'Amount',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":"required|numeric|min:1"}}',
                'order' => 7,
            ),
            134 => 
            array (
                'id' => 137,
                'data_type_id' => 18,
                'field' => 'deleted_at',
                'type' => 'timestamp',
                'display_name' => 'Deleted At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 9,
            ),
            135 => 
            array (
                'id' => 138,
                'data_type_id' => 18,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 10,
            ),
            136 => 
            array (
                'id' => 139,
                'data_type_id' => 18,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 11,
            ),
            137 => 
            array (
                'id' => 140,
                'data_type_id' => 18,
                'field' => 'detail_belongsto_invoice_relationship',
                'type' => 'relationship',
                'display_name' => 'Invoice Number',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\Models\\\\Invoice","table":"invoice","type":"belongsTo","column":"invoice_id","key":"id","label":"id","pivot_table":"category","pivot":"0","taggable":"0"}',
                'order' => 4,
            ),
            138 => 
            array (
                'id' => 141,
                'data_type_id' => 18,
                'field' => 'detail_belongsto_product_relationship',
                'type' => 'relationship',
                'display_name' => 'Product',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\Models\\\\Product","table":"product","type":"belongsTo","column":"product_id","key":"id","label":"name","pivot_table":"category","pivot":"0","taggable":"0"}',
                'order' => 6,
            ),
            139 => 
            array (
                'id' => 142,
                'data_type_id' => 18,
                'field' => 'detail_belongsto_extra_relationship',
                'type' => 'relationship',
                'display_name' => 'Discount or Surcharge',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\Models\\\\Extra","table":"extra","type":"belongsTo","column":"extra_id","key":"id","label":"name","pivot_table":"category","pivot":"0","taggable":"0"}',
                'order' => 8,
            ),
            140 => 
            array (
                'id' => 143,
                'data_type_id' => 14,
                'field' => 'invoice_belongsto_payment_method_relationship',
                'type' => 'relationship',
                'display_name' => 'Payment Method',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\Models\\\\Payment_method","table":"payment_method","type":"belongsTo","column":"payment_method_id","key":"id","label":"name","pivot_table":"category","pivot":"0","taggable":"0"}',
                'order' => 10,
            ),
            141 => 
            array (
                'id' => 144,
                'data_type_id' => 10,
                'field' => 'status',
                'type' => 'select_dropdown',
                'display_name' => 'Status',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"default":"Active","options":{"Active":"Active","Inactive":"Inactive"}}',
                'order' => 4,
            ),
            142 => 
            array (
                'id' => 145,
                'data_type_id' => 19,
                'field' => 'id',
                'type' => 'text',
                'display_name' => 'Id',
                'required' => 1,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 1,
            ),
            143 => 
            array (
                'id' => 146,
                'data_type_id' => 19,
                'field' => 'person_id',
                'type' => 'text',
                'display_name' => 'Person Id',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{}',
                'order' => 2,
            ),
            144 => 
            array (
                'id' => 147,
                'data_type_id' => 19,
                'field' => 'invoice_id',
                'type' => 'text',
                'display_name' => 'Invoice Id',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{}',
                'order' => 3,
            ),
            145 => 
            array (
                'id' => 148,
                'data_type_id' => 19,
                'field' => 'extra_id',
                'type' => 'text',
                'display_name' => 'Extra Id',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{}',
                'order' => 4,
            ),
            146 => 
            array (
                'id' => 149,
                'data_type_id' => 19,
                'field' => 'month',
                'type' => 'date',
                'display_name' => 'Month',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"validation":{"rule":"after_or_equal:01-01-2019"}}',
                'order' => 7,
            ),
            147 => 
            array (
                'id' => 150,
                'data_type_id' => 19,
                'field' => 'deleted_at',
                'type' => 'timestamp',
                'display_name' => 'Deleted At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 10,
            ),
            148 => 
            array (
                'id' => 151,
                'data_type_id' => 19,
                'field' => 'created_at',
                'type' => 'timestamp',
                'display_name' => 'Created At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 11,
            ),
            149 => 
            array (
                'id' => 152,
                'data_type_id' => 19,
                'field' => 'updated_at',
                'type' => 'timestamp',
                'display_name' => 'Updated At',
                'required' => 0,
                'browse' => 0,
                'read' => 0,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{}',
                'order' => 12,
            ),
            150 => 
            array (
                'id' => 153,
                'data_type_id' => 19,
                'field' => 'membership_belongsto_person_relationship',
                'type' => 'relationship',
                'display_name' => 'Person ID',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\Models\\\\Person","table":"person","type":"belongsTo","column":"person_id","key":"id","label":"identification","pivot_table":"category","pivot":"0","taggable":"0"}',
                'order' => 5,
            ),
            151 => 
            array (
                'id' => 154,
                'data_type_id' => 14,
                'field' => 'invoice_hasone_membership_relationship',
                'type' => 'relationship',
                'display_name' => 'membership',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{"model":"App\\\\Models\\\\Membership","table":"membership","type":"hasOne","column":"invoice_id","key":"id","label":"month","pivot_table":"category","pivot":"0","taggable":"0"}',
                'order' => 14,
            ),
            152 => 
            array (
                'id' => 155,
                'data_type_id' => 19,
                'field' => 'price',
                'type' => 'number',
                'display_name' => 'Price',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 0,
                'details' => '{"validation":{"rule":"numeric|min:0|max:999.999.999,999"},"default":"0"}',
                'order' => 8,
            ),
            153 => 
            array (
                'id' => 156,
                'data_type_id' => 19,
                'field' => 'membership_belongsto_invoice_relationship',
                'type' => 'relationship',
                'display_name' => 'Invoice number',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\Models\\\\Invoice","table":"invoice","type":"belongsTo","column":"invoice_id","key":"id","label":"id","pivot_table":"category","pivot":"0","taggable":"0"}',
                'order' => 6,
            ),
            154 => 
            array (
                'id' => 157,
                'data_type_id' => 19,
                'field' => 'membership_belongsto_extra_relationship',
                'type' => 'relationship',
                'display_name' => 'Discount',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"model":"App\\\\Models\\\\Extra","table":"extra","type":"belongsTo","column":"extra_id","key":"id","label":"name","pivot_table":"category","pivot":"0","taggable":"0"}',
                'order' => 9,
            ),
            155 => 
            array (
                'id' => 158,
                'data_type_id' => 10,
                'field' => 'person_hasone_membership_relationship',
                'type' => 'relationship',
                'display_name' => 'Memberships',
                'required' => 0,
                'browse' => 1,
                'read' => 1,
                'edit' => 0,
                'add' => 0,
                'delete' => 0,
                'details' => '{"model":"App\\\\Models\\\\Membership","table":"membership","type":"hasOne","column":"person_id","key":"id","label":"month","pivot_table":"category","pivot":"0","taggable":"0"}',
                'order' => 24,
            ),
            156 => 
            array (
                'id' => 159,
                'data_type_id' => 17,
                'field' => 'price',
                'type' => 'text',
                'display_name' => 'Price',
                'required' => 1,
                'browse' => 1,
                'read' => 1,
                'edit' => 1,
                'add' => 1,
                'delete' => 1,
                'details' => '{"validation":{"rule":"numeric|min:0|max:999.999.999,999"},"default":"0"}',
                'order' => 5,
            ),
        ));
        
        
    }
}